apiVersion: apps/v1
kind: Deployment
metadata:
  name: binarycalculator-deployment
  labels:
    app: binarycalculator
spec:
  replicas: 2
  selector:
    matchLabels:
      app: binarycalculator
  template:
    metadata:
      labels:
        app: binarycalculator
    spec:
      imagePullSecrets:                    
      - name: gcr-secret
      containers:
      - name: binarycalculator
        image: northamerica-northeast2-docker.pkg.dev/delta-rain-452016-u6/sofe3980u/binarycalculator:v3
        ports:
        - containerPort: 8080
